---
categories:
- ""
- ""
date: "2017-10-31T21:28:43-05:00"
description: ""
draft: false
image: pic10.jpg
keywords: ""
slug: hw1
title: Ipsum
---



<div id="data-manipulation" class="section level1">
<h1>Data Manipulation</h1>
<div id="problem-1-use-logical-operators-to-find-flights-that" class="section level2">
<h2>Problem 1: Use logical operators to find flights that:</h2>
<pre><code>-   Had an arrival delay of two or more hours (\&gt; 120 minutes)
-   Flew to Houston (IAH or HOU)
-   Were operated by United (`UA`), American (`AA`), or Delta (`DL`)
-   Departed in summer (July, August, and September)
-   Arrived more than two hours late, but didn&#39;t leave late
-   Were delayed by at least an hour, but made up over 30 minutes in flight</code></pre>
<pre class="r"><code>#Store flights dataframe as variable for easy reference
flights &lt;- flights

# Had an arrival delay of two or more hours (&gt; 120 minutes)
delayed_arrival_flights &lt;- flights %&gt;% 
  filter(arr_delay &gt; 120)

# Flew to Houston (IAH or HOU)
houston_flights &lt;- flights %&gt;% 
  filter(dest == &quot;IAH&quot; | dest == &quot;HOU&quot;)

# Were operated by United (`UA`), American (`AA`), or Delta (`DL`)
UA_AA_DL_flights &lt;- flights %&gt;% 
  filter(carrier == &quot;UA&quot; | carrier == &quot;AA&quot; | carrier == &quot;DL&quot;)

# Departed in summer (July, August, and September)
summer_flights &lt;- flights %&gt;% 
  filter(month %in% c(7,8,9))
  
# Arrived more than two hours late, but didn&#39;t leave late
late_arrival_flights &lt;- flights %&gt;% 
  filter(arr_delay &gt; 120 &amp; dep_delay &lt;= 0)

# Were delayed by at least an hour, but made up over 30 minutes in flight
early_arrival_flights &lt;- flights %&gt;% 
  filter(dep_delay &gt;= 60 &amp; arr_delay - dep_delay &gt;= 30)</code></pre>
</div>
<div id="problem-2-what-months-had-the-highest-and-lowest-proportion-of-cancelled-flights-interpret-any-seasonal-patterns." class="section level2">
<h2>Problem 2: What months had the highest and lowest proportion of cancelled flights? Interpret any seasonal patterns.</h2>
<pre class="r"><code># What months had the highest and lowest % of cancelled flights?

#Calculate the total number of flights per month
total_monthly_flights &lt;- flights %&gt;% 
#Group the flights dataframe by month
  group_by(month) %&gt;% 
#Count the number of rows in each group
  summarize(n())

#Calculate the number of cancellations per month 
monthly_cancellations &lt;- flights %&gt;%
#Filter for departure times that have NA (i.e., cancelled flights)
  filter(is.na(dep_time)) %&gt;%
#Group the cancelled flights by month
  group_by(month) %&gt;% 
#Count the number of cancelled flights by month
  summarize(cancelled = sum(is.na(dep_time))) %&gt;%
#Calculate the proportion of cancelled flights over the total monthly flights
  mutate(prop_cancelled = cancelled/total_monthly_flights) </code></pre>
<p><strong>Answer:</strong> February had the highest number of cancelled flights as a proportion of total monthly flights at 5.05% while October had the lowest at 0.09%. The proportion of cancelled flights are expectedly higher during the start and end of the year, as well as over the summer season as these are the times where there are relatively more flights, and hence have higher chances of cancellations.</p>
</div>
<div id="problem-3-what-plane-specified-by-the-tailnum-variable-traveled-the-most-times-from-new-york-city-airports-in-2013-please-left_join-the-resulting-table-with-the-table-planes-also-included-in-the-nycflights13-package." class="section level2">
<h2>Problem 3: What plane (specified by the <code>tailnum</code> variable) traveled the most times from New York City airports in 2013? Please <code>left_join()</code> the resulting table with the table <code>planes</code> (also included in the <code>nycflights13</code> package).</h2>
<p>For the plane with the greatest number of flights and that had more than 50 seats, please create a table where it flew to during 2013.</p>
<pre class="r"><code>#Store planes dataframe as variable for easy reference
planes &lt;- planes

#Filter flights with non-missing tail number and NYC origins
flights_filtered &lt;- flights %&gt;%
  filter(!is.na(tailnum), origin %in% c(&quot;JFK&quot;, &quot;EWR&quot;, &quot;LGA&quot;))

#Compute number of flights for each tailnum and left join with planes
flights_by_tailnum &lt;- flights_filtered %&gt;% 
#Group flights by tail number
  group_by(tailnum) %&gt;% 
#Count number of rows
  summarize(total=n()) %&gt;% 
#Arrange in descending order to identify tail number with most number of flights
  arrange(desc(total)) %&gt;%
#Left join resulting table with planes dataframe
  left_join(planes, by = &quot;tailnum&quot;)

#Filter planes with more than 50 seats and select the one with the most flights
plane_with_most_flights &lt;- flights_by_tailnum %&gt;%
#Filter data to get only those with seats grater than 50
  filter(seats&gt;50) %&gt;% 
#Identify the tail number with the most flights
  top_n(1,total) %&gt;% 
  select(tailnum)

#Get the destinations for the selected plane during 2013
destinations &lt;- flights_filtered %&gt;% 
#Filter the tail number with the most flights
  filter(tailnum == plane_with_most_flights$tailnum) %&gt;% 
#Filter the year to 2013
  filter(year == 2013) %&gt;%
#Select the destinations where the plane flew
  select(dest)

#Compute a table of frequencies of destinations
table(destinations)</code></pre>
<pre><code>## dest
## BOS LAX MCO MIA SFO SJU 
##   1 313   1  25  52   1</code></pre>
<p><strong>Answer:</strong> The plane that travelled most from New York City airports in 2013 had a tail number of N725MQ.</p>
<p>N328AA was the plane that had more than 50 seats. The destinations that it flew to in 2013 were BOS (1), LAX(313), MCO(1), MIA(25), SFO(52), and SJU(1).</p>
</div>
<div id="problem-4-the-nycflights13-package-includes-a-table-weather-that-describes-the-weather-during-2013.-use-that-table-to-answer-the-following-questions" class="section level2">
<h2>Problem 4: The <code>nycflights13</code> package includes a table (<code>weather</code>) that describes the weather during 2013. Use that table to answer the following questions:</h2>
<pre><code>-   What is the distribution of temperature (`temp`) in July 2013? Identify any important outliers in terms of the `wind_speed` variable.
-   What is the relationship between `dewp` and `humid`?
-   What is the relationship between `precip` and `visib`?</code></pre>
<pre class="r"><code>#Store weather dataframe as variable for easy reference
weather &lt;- weather

#Filter for data only for the month of July
weather %&gt;% 
  filter(month == 7) %&gt;% 
  
#Use ggplot() to plot the data
  ggplot() +
#Use temperature as the x-axis
  aes(x = temp) +
#Visualize data using histogram to see the distribution
  geom_histogram() +
#Include labels for the resulting diagram
  labs(x = &quot;Temperature&quot;, y = &quot;Counts&quot;, title = &quot;July 2013 Temperature Distribution&quot;)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/blogs/Homework1_MikeDizon_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>#Identify the quantile of wind_speed and remove NA values
quartile &lt;- quantile(weather$wind_speed, na.rm = TRUE)
#Identify interquartile ranges as difference of quartile 4 and 2
IQR &lt;- as.numeric(quartile[4]) - as.numeric(quartile[2])
#Identify outliers based on those who have wind speed values that are 3 IQR above third quartile or below the first quartile
outliers &lt;- weather%&gt;%
  filter((wind_speed &gt;= as.numeric(quartile[4]) + 3*IQR) | (wind_speed &lt;= as.numeric(quartile[2]) - 3*IQR)) %&gt;%
#Arrange filtered data to identify outlier
  arrange(desc(wind_speed))

#Plot the data to identify relationship between dewp and humid
weather %&gt;% 
  ggplot() +
#Use dewp as x-axis and humid as y-axis
  aes(x = dewp, y = humid) +
#Use scatter plot to visualize data points
  geom_point() +
#Add fitted line to the plot to identify relationship
  geom_smooth() +
#Include labels in the plot
  labs(title = &quot;Relationship between dewp and humid&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula = &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (`geom_point()`).</code></pre>
<p><img src="/blogs/Homework1_MikeDizon_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<pre class="r"><code>#Plot the data to identify relationship between precip and visib
weather %&gt;% 
  ggplot() +
#Use precip as x-axis and visib as y-axis
  aes(x = precip, y = visib) +
#Use scatter plot to visualize data points
  geom_point() +
#Add fitted line to the plot to identify relationship
  geom_smooth() +
#Scale data to see trend clearly
  scale_x_continuous(trans = &quot;log10&quot;) +
#Include labels in the plot
  labs(title = &quot;Relationship between precip and visib&quot;)</code></pre>
<pre><code>## Warning: Transformation introduced infinite values in continuous x-axis</code></pre>
<pre><code>## Warning: Transformation introduced infinite values in continuous x-axis</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula = &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<pre><code>## Warning: Removed 24366 rows containing non-finite values (`stat_smooth()`).</code></pre>
<p><img src="/blogs/Homework1_MikeDizon_files/figure-html/unnamed-chunk-5-3.png" width="672" /></p>
<p><strong>Answer:</strong> We can observe that the distribution of the temperature for July 2013 is skewed to the right.</p>
<p>There also exists a positive relationship between dewp and humid and a negative relationship betwen precip and visib.</p>
</div>
<div id="problem-5-use-the-flights-and-planes-tables-to-answer-the-following-questions" class="section level2">
<h2>Problem 5: Use the <code>flights</code> and <code>planes</code> tables to answer the following questions:</h2>
<pre><code>-   How many planes have a missing date of manufacture?
-   What are the five most common manufacturers?
-   Has the distribution of manufacturer changed over time as reflected by the airplanes flying from NYC in 2013? (Hint: you may need to use case_when() to recode the manufacturer name and collapse rare vendors into a category called Other.)</code></pre>
<pre class="r"><code>#Identify number of planes with missing date of manufacture
missing_dates &lt;- planes %&gt;% 
#Calculate the total number of planes
  summarize(sum(is.na(year)))

#Identify the five most common manufacturers
top_5_manufacturers &lt;- planes %&gt;% 
#Count the number of manufacturers and sort number in descending order
  count(manufacturer, sort = TRUE) %&gt;% 
#Extract the top five values
  top_n(5)</code></pre>
<pre><code>## Selecting by n</code></pre>
<pre class="r"><code>#Check whether the distribution of manufacturer changed over time
planes1&lt;- planes %&gt;% 
#Count the combination of manufacturer and year
  count(manufacturer, year) %&gt;% 
#Add a new column to identify category of manufacturers between those with more than five and those less than five
  mutate(man_category = case_when(n&gt;=5 ~ manufacturer, TRUE ~ &quot;Other&quot;)) %&gt;% 
#Remove those with NA values
  filter(!is.na(year))

#Recode the names in planes1 dataframe to avoid duplicate values using case_when
planes1$man_category &lt;- case_when(planes1$man_category == &quot;AIRBUS INDUSTRIE&quot; ~ &quot;AIRBUS&quot;, planes1$man_category %in% c(&quot;MCDONNELL DOUGLAS AIRCRAFT CO&quot;, &quot;MCDONNELL DOUGLAS CORPORATION&quot;) ~ &quot;MCDONNELL DOUGLAS&quot;,
  planes1$man_category == &quot;CANADAIR LTD&quot; ~ &quot;CANADAIR LTD&quot;,
  TRUE ~ planes1$man_category
)

#Use ggplot() to plot planes1 dataframe
planes1 %&gt;% 
  ggplot() +
#Use year as x-axis and the number of manufacturers as y-axis
  aes(x = year, y = n) +
#Plot using stacked columns to see shape of distribution and color based on manufacturer category and also reduce the width of each column
  geom_col(aes(fill = man_category), position = &quot;dodge&quot;) +
#Include labels in the plot
  labs(title = &quot;Distribution of manufacturing year&quot;)</code></pre>
<p><img src="/blogs/Homework1_MikeDizon_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p><strong>Answer:</strong> A total of 70 planes have missing numbers of manufacture.</p>
<p>The top five most common manufacturers are BOEING (1630), AIRBUS INDUSTRIE (400), BOMBARDIER INC (368), AIRBUS (336), and EMBRAER (299).</p>
<p>The distribution of manufacturers have significantly changed over time. Prior to the 1980s, the manufacturing of planes was dominated by small manufacturers. However, by 1990s, the industry has gradually progressed with an increasing number of manufacturers. During this period up to 2000s, we can see that the industry has been dominated by Boeing although its market share has been slightly decreasing with other competitors such as Airbus starting to gain market share.</p>
</div>
<div id="problem-6-use-the-flights-and-planes-tables-to-answer-the-following-questions" class="section level2">
<h2>Problem 6: Use the <code>flights</code> and <code>planes</code> tables to answer the following questions:</h2>
<pre><code>-   What is the oldest plane (specified by the tailnum variable) that flew from New York City airports in 2013?
-   How many airplanes that flew from New York City are included in the planes table?</code></pre>
<pre class="r"><code>#Identify the oldest plane from NYC airports in 2013
oldest_plane &lt;- planes %&gt;% 
#Right join the planes dataframe with the flights dataframe by tail number
  right_join(flights, by = &quot;tailnum&quot;) %&gt;% 
#Arrange data in ascending order by year
  arrange(year.x) %&gt;% 
#Select the tail number and year columns only
  select(tailnum, year.x) %&gt;% 
#Extract the top row from the dataframe to see oldest plane
  head(1)

#Identify the number of airplanes that flew from NYC that are included in the planes table
planes_nyc &lt;- flights %&gt;% 
#Inner join the planes and flights dataframe by tail number
  inner_join(planes, by = &quot;tailnum&quot;) %&gt;% 
#Count the number of planes using their tail numbers 
  summarize(n = n_distinct(tailnum))</code></pre>
<p><strong>Answer:</strong> The oldest plane that flew from New York City airports in 2013 was the N381AA, which was manufactured in 1956.</p>
<p>The number of airplanes that flew from New York City that are included in the planes table is 3322.</p>
</div>
<div id="problem-7-use-the-nycflights13-to-answer-the-following-questions" class="section level2">
<h2>Problem 7: Use the <code>nycflights13</code> to answer the following questions:</h2>
<pre><code>-   What is the median arrival delay on a month-by-month basis in each airport?
-   For each airline, plot the median arrival delay for each month and origin airport.</code></pre>
<pre class="r"><code>#Identify median arrival delay on a monthly basis for each airport
median_arrival_delay &lt;- flights %&gt;% 
#Select carrier, origin, month, and arr_delay columns from flights dataframe
  select(carrier, origin, month, arr_delay) %&gt;%
#Group data by carrier, origin, and month
  group_by(carrier, origin, month) %&gt;%
#Calculate median of arrival delay
  summarize(median_delay = median(arr_delay, na.rm = TRUE), .groups = &quot;drop&quot;)

#Use ggplot() to plot median arrival delay
median_arrival_delay %&gt;% 
ggplot() +
#Use month as x-axis, median delay as y-axis, and color by carrier
  aes(x = month, y = median_delay, color = carrier) +
#Plot the data using a line chart
  geom_line() +
#Obtain subplots for each airport
  facet_wrap(~ origin)</code></pre>
<p><img src="/blogs/Homework1_MikeDizon_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="problem-8-lets-take-a-closer-look-at-what-carriers-service-the-route-to-san-francisco-international-sfo.-join-the-flights-and-airlines-tables-and-count-which-airlines-flew-the-most-to-sfo.-produce-a-new-dataframe-fly_into_sfo-that-contains-three-variables-the-name-of-the-airline-e.g.-united-air-lines-inc.-not-ua-the-count-number-of-times-it-flew-to-sfo-and-the-percent-of-the-trips-that-that-particular-airline-flew-to-sfo." class="section level2">
<h2>Problem 8: Let’s take a closer look at what carriers service the route to San Francisco International (SFO). Join the <code>flights</code> and <code>airlines</code> tables and count which airlines flew the most to SFO. Produce a new dataframe, <code>fly_into_sfo</code> that contains three variables: the <code>name</code> of the airline, e.g., <code>United Air Lines Inc.</code> not <code>UA</code>, the count (number) of times it flew to SFO, and the <code>percent</code> of the trips that that particular airline flew to SFO.</h2>
<pre class="r"><code>#Left join airlines dataframe with flights dataframe and store into variable fly_into_sfo
fly_into_sfo &lt;- flights %&gt;% 
  left_join(airlines, by = &quot;carrier&quot;) %&gt;% 
#Filter the San Francisco destination
  filter(dest == &quot;SFO&quot;) %&gt;%
#Group data by name of airline
  group_by(name) %&gt;% 
#Count the number of flights to SFO per airline and calculate the corresponding proportion of total flights 
  summarize(count = n(), percent = n() / nrow(flights), .groups = &quot;drop&quot;)</code></pre>
<p><strong>Answer:</strong> It can be observed that of all the flights with San Francisco as destination, United Airlines had the most at 6819 while JetBlue Airways had the least at 1035.</p>
<p>And here is some bonus ggplot code to plot your dataframe</p>
<pre class="r"><code>fly_into_sfo %&gt;% 
  
  # sort &#39;name&#39; of airline by the numbers it times to flew to SFO
  mutate(name = fct_reorder(name, count)) %&gt;% 
  
  ggplot() +
  
  aes(x = count, 
      y = name) +
  
  # a simple bar/column plot
  geom_col() +
  
  # add labels, so each bar shows the % of total flights 
  geom_text(aes(label = percent),
             hjust = 1, 
             colour = &quot;white&quot;, 
             size = 5)+
  
  # add labels to help our audience  
  labs(title=&quot;Which airline dominates the NYC to SFO route?&quot;, 
       subtitle = &quot;as % of total flights in 2013&quot;,
       x= &quot;Number of flights&quot;,
       y= NULL) +
  
  theme_minimal() + 
  
  # change the theme-- i just googled those , but you can use the ggThemeAssist add-in
  # https://cran.r-project.org/web/packages/ggThemeAssist/index.html
  
  theme(#
    # so title is left-aligned
    plot.title.position = &quot;plot&quot;,
    
    # text in axes appears larger        
    axis.text = element_text(size=12),
    
    # title text is bigger
    plot.title = element_text(size=18)
      ) +

  # add one final layer of NULL, so if you comment out any lines
  # you never end up with a hanging `+` that awaits another ggplot layer
  NULL</code></pre>
<p><img src="/blogs/Homework1_MikeDizon_files/figure-html/ggplot-flights-toSFO-1.png" width="672" /></p>
</div>
<div id="problem-9-lets-take-a-look-at-cancellations-of-flights-to-sfo.-we-create-a-new-dataframe-cancellations-as-follows" class="section level2">
<h2>Problem 9: Let’s take a look at cancellations of flights to SFO. We create a new dataframe <code>cancellations</code> as follows</h2>
<pre class="r"><code>cancellations &lt;- flights %&gt;% 
  
  # just filter for destination == &#39;SFO&#39;
  filter(dest == &#39;SFO&#39;) %&gt;% 
  
  # a cancelled flight is one with no `dep_time` 
  filter(is.na(dep_time))</code></pre>
<p>I want you to think how we would organise our data manipulation to create the following plot. No need to write the code, just explain in words how you would go about it.</p>
<p><strong>Answer:</strong> I would start by creating a new dataframe that would summarize the cancellations by month, carrier, and airport origin. I would then use the <code>geom_col()</code> under the <code>ggplot()</code> function to do a bar graph for the resulting dataset. Finally, I would integrate the <code>facet_wrap()</code> function to organize the data into subplots organized according to airport origin and carrier.</p>
<p><img src="images/sfo-cancellations.png" /></p>
</div>
<div id="problem-10-on-your-own-hollywood-age-gap" class="section level2">
<h2>Problem 10: On your own – Hollywood Age Gap</h2>
<p>The website <a href="https://hollywoodagegap.com" class="uri">https://hollywoodagegap.com</a> is a record of <em>THE AGE DIFFERENCE IN YEARS BETWEEN MOVIE LOVE INTERESTS</em>. This is an informational site showing the age gap between movie love interests and the data follows certain rules:</p>
<ul>
<li>The two (or more) actors play actual love interests (not just friends, coworkers, or some other non-romantic type of relationship)</li>
<li>The youngest of the two actors is at least 17 years old</li>
<li>No animated characters</li>
</ul>
<p>The age gaps dataset includes “gender” columns, which always contain the values “man” or “woman”. These values appear to indicate how the characters in each film identify and some of these values do not match how the actor identifies. We apologize if any characters are misgendered in the data!</p>
<p>The following is a data dictionary of the variables used</p>
<table>
<colgroup>
<col width="26%" />
<col width="26%" />
<col width="47%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="left">class</th>
<th align="left">description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">movie_name</td>
<td align="left">character</td>
<td align="left">Name of the film</td>
</tr>
<tr class="even">
<td align="left">release_year</td>
<td align="left">integer</td>
<td align="left">Release year</td>
</tr>
<tr class="odd">
<td align="left">director</td>
<td align="left">character</td>
<td align="left">Director of the film</td>
</tr>
<tr class="even">
<td align="left">age_difference</td>
<td align="left">integer</td>
<td align="left">Age difference between the characters in whole years</td>
</tr>
<tr class="odd">
<td align="left">couple_number</td>
<td align="left">integer</td>
<td align="left">An identifier for the couple in case multiple couples are listed for this film</td>
</tr>
<tr class="even">
<td align="left">actor_1_name</td>
<td align="left">character</td>
<td align="left">The name of the older actor in this couple</td>
</tr>
<tr class="odd">
<td align="left">actor_2_name</td>
<td align="left">character</td>
<td align="left">The name of the younger actor in this couple</td>
</tr>
<tr class="even">
<td align="left">character_1_gender</td>
<td align="left">character</td>
<td align="left">The gender of the older character, as identified by the person who submitted the data for this couple</td>
</tr>
<tr class="odd">
<td align="left">character_2_gender</td>
<td align="left">character</td>
<td align="left">The gender of the younger character, as identified by the person who submitted the data for this couple</td>
</tr>
<tr class="even">
<td align="left">actor_1_birthdate</td>
<td align="left">date</td>
<td align="left">The birthdate of the older member of the couple</td>
</tr>
<tr class="odd">
<td align="left">actor_2_birthdate</td>
<td align="left">date</td>
<td align="left">The birthdate of the younger member of the couple</td>
</tr>
<tr class="even">
<td align="left">actor_1_age</td>
<td align="left">integer</td>
<td align="left">The age of the older actor when the film was released</td>
</tr>
<tr class="odd">
<td align="left">actor_2_age</td>
<td align="left">integer</td>
<td align="left">The age of the younger actor when the film was released</td>
</tr>
</tbody>
</table>
<pre class="r"><code>age_gaps &lt;- readr::read_csv(&#39;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-02-14/age_gaps.csv&#39;)</code></pre>
<pre><code>## Rows: 1155 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (6): movie_name, director, actor_1_name, actor_2_name, character_1_gend...
## dbl  (5): release_year, age_difference, couple_number, actor_1_age, actor_2_age
## date (2): actor_1_birthdate, actor_2_birthdate
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>How would you explore this data set? Here are some ideas of tables/ graphs to help you with your analysis</p>
<ul>
<li>How is <code>age_difference</code> distributed? What’s the ‘typical’ <code>age_difference</code> in movies?</li>
</ul>
<pre class="r"><code>#Use ggplot() to identify the shape of distribution of age difference
age_gaps %&gt;% 
ggplot() +
#Use the age difference as x-axis
  aes(x = age_difference) +
#Plot data using histogram and adjust binwidth 
  geom_histogram(binwidth = 5) +
#Include labels in the plot
  labs(x = &quot;Age Difference&quot;, y = &quot;Count&quot;, 
       title = &quot;Distribution of Age Difference in Movies&quot;)</code></pre>
<p><img src="/blogs/Homework1_MikeDizon_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>#Compute for the mean of the age difference
mean(age_gaps$age_difference)</code></pre>
<pre><code>## [1] 10.42424</code></pre>
<pre class="r"><code>#Compute for the median of the age difference
median(age_gaps$age_difference)</code></pre>
<pre><code>## [1] 8</code></pre>
<p><strong>Answer:</strong> The distribution of the age difference is skewed to the right, which means that most values are within the 0-20 range.</p>
<p>The mean age difference is 10.4 while the median age difference is 8.</p>
<ul>
<li>The <code>half plus seven\</code> rule. Large age disparities in relationships carry certain stigmas. One popular rule of thumb is the <a href="https://en.wikipedia.org/wiki/Age_disparity_in_sexual_relationships#The_.22half-your-age-plus-seven.22_rule">half-your-age-plus-seven</a> rule. This rule states you should never date anyone under half your age plus seven, establishing a minimum boundary on whom one can date. In order for a dating relationship to be acceptable under this rule, your partner’s age must be:</li>
</ul>
<p><span class="math display">\[\frac{\text{Your age}}{2} + 7 \\\\\\\&lt; \text{Partner Age} \\\\\\\&lt; (\text{Your age} - 7) \\\\\\\* 2\]</span> How frequently does this rule apply in this dataset?</p>
<pre class="r"><code>#Mutate age_gaps dataframe
age_gaps &lt;- age_gaps %&gt;%
#Add half_plus_seven column which computes lower bound for the age difference
  mutate(half_plus_seven = ((actor_1_age) / 2) + 7,
#Add age_max column which computes upper bound for the age difference
         age_max = ((actor_1_age) - 7) * 2,
#Add acceptable column which compares whether the age difference is within the established lower and upper bounds 
         acceptable = age_difference &gt;= half_plus_seven &amp; age_difference &lt;= age_max)

# calculate the proportion of acceptable age differences
prop_acceptable &lt;- mean(age_gaps$acceptable)

# calculate the frequency of acceptable age differences
freq_acceptable &lt;- sum(age_gaps$acceptable)</code></pre>
<p><strong>Answer:</strong> The half-your-age-plus-seven rule applies in 0.87% of cases (10 out of 1155). In other words, majority of cases do not conform to the rule in terms of age difference.</p>
<ul>
<li>Which movie has the greatest number of love interests?</li>
</ul>
<pre class="r"><code>#Group data by the name of movie
most_love_interests &lt;- age_gaps %&gt;%
  group_by(movie_name) %&gt;%
#Compute for the sum of couple numbers per movie
  summarise(num_love_interests = sum(couple_number)) %&gt;%
#Arrange values in descending order
  arrange(desc(num_love_interests)) %&gt;%
#Extract the top row
  head(1)</code></pre>
<p><strong>Answer:</strong> Love Actually was the movie with the greatest number of love interests at 28.</p>
<ul>
<li>Which actors/ actresses have the greatest number of love interests in this dataset?</li>
</ul>
<pre class="r"><code>#Group data by name of actors
love_interests &lt;- age_gaps %&gt;%
  group_by(actor_1_name) %&gt;%
#Compute for distinct number of love interest for each specific actor
  summarise(num_love_interests = n_distinct(actor_2_name)) %&gt;%
#Arrange values in descending order
  arrange(desc(num_love_interests)) %&gt;% 
#Extract the top 5 actors
  head(5)</code></pre>
<p><strong>Answer:</strong> The top five actors with the greatest number of love interests are Keanu Reeves (23), Adam Sandler (17), Roger Moore (16), Sean Connery (15), and Harrison Ford (13).</p>
<ul>
<li>Is the mean/median age difference staying constant over the years (1935 - 2022)?</li>
</ul>
<pre class="r"><code>#Group data by release year
age_diff_by_year &lt;- age_gaps %&gt;%
  group_by(release_year) %&gt;%
#Calculate the mean and meadian age difference by release year
  summarise(mean_age_diff = mean(age_difference), median_age_diff = median(age_difference))

#Use ggplot() to plot the mean and median age difference
age_diff_by_year %&gt;% 
ggplot() +
#Use release year as x-axis and mean age difference as y-axis
  aes(x = release_year, y = mean_age_diff) +
#Plot data using line chart with blue color
  geom_line(color = &quot;blue&quot;) +
#Use line chart to also plot the median age difference with red as color
  geom_line(aes(y = median_age_diff), color = &quot;red&quot;) +
#Include labels in the plot
  labs(x = &quot;Year&quot;, y = &quot;Age Difference (Years)&quot;, title = &quot;Mean/Median Age Difference Over Time&quot;)</code></pre>
<p><img src="/blogs/Homework1_MikeDizon_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p><strong>Answer:</strong> The mean and median of the age difference do not stay constant over time. It has peaked during the 1950s and slightly fell off during the 1960s-70s. However, it started to slightly increase again and peak by 1985. Around 2000s, the mean and median have once again decreased, but are starting to increase again in recent times.</p>
<ul>
<li>How frequently does Hollywood depict same-gender love interests?</li>
</ul>
<pre class="r"><code>#Filter for data with the same gender for both characters
same_gender &lt;- age_gaps %&gt;% 
  filter(character_1_gender == character_2_gender) %&gt;%
#Count the values
  count()</code></pre>
<p><strong>Answer:</strong> From 1935-2022, there have only been 23 instances wherein there were same-gender love interests.</p>
</div>
</div>
<div id="deliverables" class="section level1">
<h1>Deliverables</h1>
<p>There is a lot of explanatory text, comments, etc. You do not need these, so delete them and produce a stand-alone document that you could share with someone. Render the edited and completed Quarto Markdown (qmd) file as a Word document (use the “Render” button at the top of the script editor window) and upload it to Canvas. You must be commiting and pushing tour changes to your own Github repo as you go along.</p>
</div>
<div id="details" class="section level1">
<h1>Details</h1>
<ul>
<li>Who did you collaborate with: N/A</li>
<li>Approximately how much time did you spend on this problem set: 1 day</li>
<li>What, if anything, gave you the most trouble: Using ggplots() for sophisticated graphs</li>
</ul>
</div>
